# Makefile for TI-84 CE Math Solver
# Based on the CE C/C++ Toolchain standard template

# Application definition
NAME = TEXTBOX
DESCRIPTION = "With ICON"
ICON = assets/icon.png

include ../makefile.common