# Makefile for TI-84 CE Math Solver
# Based on the CE C/C++ Toolchain standard template

# Application definition
NAME = MATHSLVR
DESCRIPTION = "TI-84 CE Math Solver"
#ICON = icon.png

include ../makefile.common