# Makefile for TI-84 CE Math Solver
# Based on the CE C/C++ Toolchain standard template

# Application definition
NAME = INPUTSTR
DESCRIPTION = "User input testbed"
#ICON = icon.png

include ../makefile.common